version: '3.4'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - '0.0.0.0:3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: rest_api
      MYSQL_ROOT_HOST: "%"
    networks:
      - subnet_0
    restart: on-failure
    volumes:
      - mysql-volume:/var/lib/mysql

  api:
    container_name: api
    build:
      context: ./
    restart: on-failure
    networks:
      - subnet_0
    environment:
      JAVA_OPTIONS: -Xmx400m
    volumes:
      - ./:/app

networks:
  subnet_0:
    driver: bridge

volumes:
  mysql-volume: {}
