version: '3.4'

services:
  api:
    container_name: api
    hostname: api
    image: juliocesarmidia/java-spring-rest-api:latest
    build:
      context: ./
    restart: on-failure
    networks:
      - subnet_0
    ports:
      - 8000:8000
    environment:
      JAVA_OPTIONS: -Xmx400m
      JDBC_HOST: ${JDBC_HOST}
      JDBC_PORT: ${JDBC_PORT}
      JDBC_USER: ${JDBC_USER}
      JDBC_PASS: ${JDBC_PASS}
      JDBC_DATABASE: ${JDBC_DATABASE}
      JWT_TOKEN_SECRET_KEY: ${JWT_TOKEN_SECRET_KEY:-secret}
      JWT_TOKEN_EXPIRE_LENGTH: ${JWT_TOKEN_EXPIRE_LENGTH:-3600000}
    volumes:
      - $PWD/uploads/:/usr/src/app/uploads/

  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql:8.0
    restart: on-failure
    networks:
      - subnet_0
    ports:
      - '3336:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${JDBC_PASS}
      MYSQL_DATABASE: ${JDBC_DATABASE}
      MYSQL_ROOT_HOST: "%"
    volumes:
      - mysql-volume:/var/lib/mysql

  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus:latest
    command: [
      "--config.file=/prometheus-config/prometheus.yaml",
      "--web.config.file=/prometheus-config/web.yaml"
    ]
    restart: on-failure
    networks:
      - subnet_0
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/:/prometheus-config
      - prometheus-data:/prometheus

networks:
  subnet_0:
    driver: bridge

volumes:
  mysql-volume: {}
  prometheus-data: {}
