version: '3.4'

services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    restart: on-failure
    networks:
      - subnet_0
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    restart: on-failure
    networks:
      - subnet_0
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka-data:/var/lib/kafka/data

  java-kafka:
    container_name: java-kafka
    build:
      context: ./
    restart: on-failure
    networks:
      - subnet_0
    environment:
      JAVA_OPTIONS: -Xmx400m
      BOOTSTRAP_SERVERS: kafka:9092
      TOPIC_NAME: topic_0
    volumes:
      - ./:/app

networks:
  subnet_0:
    driver: bridge

volumes:
  kafka-data: {}
  zookeeper-data: {}
