global:
  scrape_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets:
      - localhost:9090

    basic_auth:
      username: admin
      password: admin

  - job_name: api
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets:
      - api:8000
